In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.10.0'

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [14]:
ann.compile(optimizer='adam',metrics=['accuracy'],loss='binary_crossentropy')

In [15]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 2ms/step - loss: 0.5874 - accuracy: 0.7001
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4778 - accuracy: 0.7940
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4531 - accuracy: 0.7990
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4372 - accuracy: 0.8027
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4235 - accuracy: 0.8073
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4098 - accuracy: 0.8141
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3960 - accuracy: 0.8236
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3837 - accuracy: 0.8350
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3741 - accuracy: 0.8413
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3676 - accura

In [24]:
from numpy import array
Xnew = array([[1,0,0,600,1,40,3,60000,2,1,1,50000]])
print(ann.predict(sc.transform(Xnew))>0.5)

1/1 [==============================] - 0s 90ms/step
[[False]]


In [25]:
y_pred = ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 4ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1579   16]
 [ 321   84]]


0.8315